// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types


type UserLoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UsrLoginReply struct {
	Token string `json:"token"`
}
