// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type SendMessageReply struct {
}

type SendMessageRequest struct {
	AppKey     string `json:"app_key"`
	ProductKey string `json:"product_key"`
	DeviceKey  string `json:"device_key"`
	Data       string `json:"data"`
	Sign       string `json:"sign"`
}
